In [333]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 

from sklearn.neighbors import KNeighborsClassifier

from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn.model_selection import GridSearchCV 
from sklearn.model_selection import RandomizedSearchCV

from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.impute import KNNImputer

from sklearn import datasets

In [334]:
data = {
    "PID": [
        100001000, 100002000, 100003000, 100004000,
        100005000, 100006000, 100007000, 100008000,
        100009000, 100010000, 100011000, 100012000
    ],

    "ST_NUM": [
        104, 197, np.nan, 201,
        203, np.nan, 207, 210,
        np.nan, 215, 217, np.nan
    ],

    "ST_NAME": [
        "PUTNAM", "LEXINGTON", "LEXINGTON", "BERKELEY",
        "BERKELEY", "BERKELEY", "WASHINGTON", "WASHINGTON",
        "TREMONT", "TREMONT", "TREMONT", "TREMONT"
    ],

    "OWN_OCCUPIED": [
        "Y", "N", "N", "Y",
        "Y", "Y", np.nan, "Y",
        "Y", np.nan, "N", "Y"
    ],

    "NUM_BEDROOMS": [
        3, 3, np.nan, 1,
        3, np.nan, 2, 1,
        np.nan, 2, 3, np.nan
    ],

    "NUM_BATH": [
        1, 1.5, 1, np.nan,
        2, 1, np.nan, 1,
        2, np.nan, 2, 1
    ],

    "SQ_FT": [
        1000, np.nan, 850, 700,
        1600, 800, np.nan, 1200,
        950, np.nan, 1800, 2000
    ]
}

df = pd.DataFrame(data)

In [335]:
df.isna()

      PID  ST_NUM  ST_NAME  OWN_OCCUPIED  NUM_BEDROOMS  NUM_BATH  SQ_FT
0   False   False    False         False         False     False  False
1   False   False    False         False         False     False   True
2   False    True    False         False          True     False  False
3   False   False    False         False         False      True  False
4   False   False    False         False         False     False  False
5   False    True    False         False          True     False  False
6   False   False    False          True         False      True   True
7   False   False    False         False         False     False  False
8   False    True    False         False          True     False  False
9   False   False    False          True         False      True   True
10  False   False    False         False         False     False  False
11  False    True    False         False          True     False  False

In [336]:
df

          PID  ST_NUM     ST_NAME OWN_OCCUPIED  NUM_BEDROOMS  NUM_BATH   SQ_FT
0   100001000   104.0      PUTNAM            Y           3.0       1.0  1000.0
1   100002000   197.0   LEXINGTON            N           3.0       1.5     NaN
2   100003000     NaN   LEXINGTON            N           NaN       1.0   850.0
3   100004000   201.0    BERKELEY            Y           1.0       NaN   700.0
4   100005000   203.0    BERKELEY            Y           3.0       2.0  1600.0
5   100006000     NaN    BERKELEY            Y           NaN       1.0   800.0
6   100007000   207.0  WASHINGTON          NaN           2.0       NaN     NaN
7   100008000   210.0  WASHINGTON            Y           1.0       1.0  1200.0
8   100009000     NaN     TREMONT            Y           NaN       2.0   950.0
9   100010000   215.0     TREMONT          NaN           2.0       NaN     NaN
10  100011000   217.0     TREMONT            N           3.0       2.0  1800.0
11  100012000     NaN     TREMONT            Y           NaN       1.0  2000.0

In [337]:
df['NUM_BATH'] = df['NUM_BATH'].apply(lambda x: int(x) if not pd.isna(x) else np.nan)

In [338]:
# def occupation(x):
#     if x == 'Y':
#         return 1
#     elif x == 'N':
#         return 0
#     else:
#         return np.nan
# df['OWN_OCCUPIED'] = df['OWN_OCCUPIED'].apply(occupation)

In [339]:
encoder1 = LabelEncoder()
encoder1.fit(df['ST_NAME'])
df['ST_NAME'] = encoder1.transform(df['ST_NAME'])

In [340]:
encoder1.classes_

array(['BERKELEY', 'LEXINGTON', 'PUTNAM', 'TREMONT', 'WASHINGTON'],
      dtype=object)

In [341]:
encoder2 =  LabelEncoder()
encoder2.fit(['Y', 'N'])
df['OWN_OCCUPIED'] = df['OWN_OCCUPIED'].apply(lambda x: encoder2.transform([x])[0] if x in ['Y', 'N'] else x)

In [342]:
encoder2.classes_

array(['N', 'Y'], dtype='<U1')

In [343]:
df

          PID  ST_NUM  ST_NAME  OWN_OCCUPIED  NUM_BEDROOMS  NUM_BATH   SQ_FT
0   100001000   104.0        2           1.0           3.0       1.0  1000.0
1   100002000   197.0        1           0.0           3.0       1.0     NaN
2   100003000     NaN        1           0.0           NaN       1.0   850.0
3   100004000   201.0        0           1.0           1.0       NaN   700.0
4   100005000   203.0        0           1.0           3.0       2.0  1600.0
5   100006000     NaN        0           1.0           NaN       1.0   800.0
6   100007000   207.0        4           NaN           2.0       NaN     NaN
7   100008000   210.0        4           1.0           1.0       1.0  1200.0
8   100009000     NaN        3           1.0           NaN       2.0   950.0
9   100010000   215.0        3           NaN           2.0       NaN     NaN
10  100011000   217.0        3           0.0           3.0       2.0  1800.0
11  100012000     NaN        3           1.0           NaN       1.0  2000.0

In [344]:
model = KNNImputer(n_neighbors=2,)

In [345]:
r = model.fit_transform(df)
d = pd.DataFrame(r, columns=df.columns)

In [348]:
df

          PID  ST_NUM  ST_NAME  OWN_OCCUPIED  NUM_BEDROOMS  NUM_BATH   SQ_FT
0   100001000   104.0        2           1.0           3.0       1.0  1000.0
1   100002000   197.0        1           0.0           3.0       1.0     NaN
2   100003000     NaN        1           0.0           NaN       1.0   850.0
3   100004000   201.0        0           1.0           1.0       NaN   700.0
4   100005000   203.0        0           1.0           3.0       2.0  1600.0
5   100006000     NaN        0           1.0           NaN       1.0   800.0
6   100007000   207.0        4           NaN           2.0       NaN     NaN
7   100008000   210.0        4           1.0           1.0       1.0  1200.0
8   100009000     NaN        3           1.0           NaN       2.0   950.0
9   100010000   215.0        3           NaN           2.0       NaN     NaN
10  100011000   217.0        3           0.0           3.0       2.0  1800.0
11  100012000     NaN        3           1.0           NaN       1.0  2000.0

In [349]:
d

            PID  ST_NUM  ST_NAME  OWN_OCCUPIED  NUM_BEDROOMS  NUM_BATH   SQ_FT
0   100001000.0   104.0      2.0           1.0           3.0       1.0  1000.0
1   100002000.0   197.0      1.0           0.0           3.0       1.0   925.0
2   100003000.0   199.0      1.0           0.0           2.0       1.0   850.0
3   100004000.0   201.0      0.0           1.0           1.0       1.5   700.0
4   100005000.0   203.0      0.0           1.0           3.0       2.0  1600.0
5   100006000.0   205.0      0.0           1.0           2.5       1.0   800.0
6   100007000.0   207.0      4.0           1.0           2.0       1.0  1000.0
7   100008000.0   210.0      4.0           1.0           1.0       1.0  1200.0
8   100009000.0   212.5      3.0           1.0           1.5       2.0   950.0
9   100010000.0   215.0      3.0           0.5           2.0       2.0  1375.0
10  100011000.0   217.0      3.0           0.0           3.0       2.0  1800.0
11  100012000.0   216.0      3.0           1.0           2.5       1.0  2000.0